---
- include: bootstrap.yml
  tags:
    - bootstrap
    - pypy

- set_fact:
    ansible_python_interpreter: "{{ coreos_bootstrap_dir }}/python"

- block:

    - name: Check if we need to install pip
      shell: "{{ ansible_python_interpreter }} -m pip --version"
      register: coreos_python_pip_check
      changed_when: False

  tags:
    - pip

  rescue:

    - name: Download pip installer
      get_url:
        url: "{{ coreos_bootstrap_pip_download_link }}"
        dest: "{{ coreos_bootstrap_pip_download_dest }}"

    - name: Install pip
      shell:
        "{{ ansible_python_interpreter }} \
         {{ coreos_bootstrap_pip_download_dest }}/{{ coreos_bootstrap_pip_download_file }}"

    - name: Remove pip installer
      file:
        path: "{{ coreos_bootstrap_pip_download_dest }}/{{ coreos_bootstrap_pip_download_file }}"
        state: absent
